// Zero-dependency build: concatenate the lib/ ES modules (all first-party, no external imports)
// in dependency order into a single-file ESM bundle and a window.Sniffies IIFE global bundle.
// No bundler. Fails loudly on any drift that would otherwise ship a broken bundle.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';

// Dependency order: errors → limiter → api/observe → dom → compose → index.
const ORDER = ['errors', 'limiter', 'api', 'observe', 'dom', 'compose', 'index'];

// Guard: ORDER must cover lib/*.js exactly (a new module missing from ORDER would build a bundle
// without it while build:check still passes).
const onDisk = readdirSync(new URL('../lib/', import.meta.url)).filter((f) => f.endsWith('.js')).map((f) => f.slice(0, -3)).sort();
if (onDisk.join(',') !== [...ORDER].sort().join(',')) {
  throw new Error(`build-lib: ORDER drift — lib/ has [${onDisk}], ORDER has [${[...ORDER].sort()}]`);
}

const read = (name) => readFileSync(new URL(`../lib/${name}.js`, import.meta.url), 'utf8');
const exportNames = (src) => [
  ...[...src.matchAll(/^export\s+(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]),
  ...[...src.matchAll(/^export\s*\{([^}]*)\}/gm)].flatMap((m) => m[1].split(',').map((s) => s.trim().split(/\s+as\s+/).pop().trim()).filter(Boolean)),
];

// `dom` and `compose` are consumed as namespace objects (import * as dom). Rebuild those namespaces
// from each module's own export list so a rename can never ship a bundle that throws at load.
const domNames = [...new Set(exportNames(read('dom')))];
const composeNames = [...new Set(exportNames(read('compose')))];

// Strip intra-lib imports, bare re-export statements, and the `export` keyword on declarations, so
// the modules collapse into plain top-level declarations in one shared scope.
const strip = (src) => src
  .replace(/^\s*import[^;]*from\s*['"]\.\/[^'"]+['"];?\s*$/gm, '')
  .replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '')
  .replace(/^(\s*)export\s+(default\s+)?(async\s+function|function|class|const|let|var)\b/gm, '$1$3');

let body = '';
for (const name of ORDER) {
  // index.js imports the dom/compose namespaces + siblings (all stripped); its own `export const
  // VERSION` survives strip as a plain declaration and is the single VERSION definition. The dom
  // and compose namespace objects are appended after the module bodies (DOM_NS / COMPOSE_NS).
  body += `\n// ---- lib/${name}.js ----\n${strip(read(name))}\n`;
}

// Guard: no module syntax survived the strip (would ship a SyntaxError into the IIFE).
const leak = body.match(/^\s*(?:export|import)\b.*$/m);
if (leak) throw new Error(`build-lib: unstripped module syntax survived strip():\n${leak[0]}`);

// Guard: no duplicate top-level declaration across modules (a hard SyntaxError in one scope).
const decls = [...body.matchAll(/^(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);
const dup = [...new Set(decls.filter((n, i) => decls.indexOf(n) !== i))];
if (dup.length) throw new Error(`build-lib: duplicate top-level names across modules: ${dup}`);

const DOM_NS = `const dom = { ${domNames.join(', ')} };`;
const COMPOSE_NS = `const compose = { ${composeNames.join(', ')} };`;
const NAMES = 'createClient, createApi, createObserver, createLimiter, computeLastActiveTs, extractAttitudeFromPartial, decodeSocketFrame, isSniffiesApiUrl, SniffiesError, SniffiesAllBasesError, SniffiesTimeoutError, dom, compose, VERSION';

mkdirSync(new URL('../dist/', import.meta.url), { recursive: true });
const header = '// AUTO-GENERATED by scripts/build-lib.mjs — do not edit. Source: lib/*.js\n';

writeFileSync(new URL('../dist/sniffies.esm.js', import.meta.url), `${header}${body}\n${DOM_NS}\n${COMPOSE_NS}\nexport { ${NAMES} };\n`);

const iife = `${header}(function () {\n'use strict';\n${body}\n${DOM_NS}\n${COMPOSE_NS}\nvar root = (typeof window !== 'undefined') ? window : globalThis;\nroot.Sniffies = { ${NAMES} };\n})();\n`;
writeFileSync(new URL('../dist/sniffies.global.js', import.meta.url), iife);

console.log('Built dist/sniffies.esm.js + dist/sniffies.global.js');
